<?php

return [
    'projects' => [
        [
            'name' => 'Citas CRIT', 'slug' => 'citas-crit', 'type' => 'Mobile App', 'status' => 'Production',
            'summary' => 'An Android app designed to help CRIT families organize and review appointments clearly and practically.',
            'problem' => 'Appointment information can be difficult to review and organize in everyday life.',
            'solution' => 'A mobile experience focused on clarity, fast access and practical value for families.',
            'stack' => ['Flutter','Dart','Android'], 'signal' => 'Published on Google Play',
            'context' => 'The product grew from an everyday need: keeping CRIT appointments organized in one accessible place, with a simple experience for families who need to review information without friction.',
            'capabilities' => ['Schedule import and organization','Clear appointment review','Local information persistence','Distribution as an Android app'],
            'architecture' => ['Flutter for a consistent mobile experience','Local persistence to keep the schedule available','Appointment information processing inside the app','Publishing and updates through Google Play'],
            'media' => [],
        ],
        [
            'name' => 'Digital Persona SchoolBio', 'slug' => 'digital-persona-schoolbio', 'type' => 'Biometrics · Desktop', 'status' => 'Product',
            'summary' => 'A school biometric control system connecting fingerprint readers, a Windows terminal and platform services for attendance and identity.',
            'problem' => 'On-site school operations need to identify students quickly while keeping information synchronized with the platform.',
            'solution' => 'A biometric client for fingerprint enrollment, verification and identification, with local operation and synchronization through the SchoolBio API.',
            'stack' => ['C#','WinForms','.NET Framework 4.8','Biometrics','API'], 'signal' => 'Software + biometric hardware + API',
            'context' => 'SchoolBio extends school software to the physical entry point: a Windows terminal communicates with the biometric reader, manages local data and synchronizes events with the platform.',
            'capabilities' => ['Fingerprint enrollment','Biometric verification and identification','Attendance recording','Student and academic period management','Synchronization with SchoolBio API'],
            'architecture' => ['C# / Windows Forms client on .NET Framework 4.8','Digital Persona hardware integration','Local repositories for terminal operation','Biometric services for enrollment and identification','API synchronization with the SchoolBio platform'],
            'media' => [],
        ],
        [
            'name' => 'Baseball App', 'slug' => 'baseball-app', 'type' => 'Mobile Product', 'status' => 'Product',
            'summary' => 'An Android baseball scorekeeper with play-by-play tracking, statistics, exports and a Free/Pro experience.',
            'problem' => 'Recording a full game and turning every play into useful statistics often requires separate tools or manual processes.',
            'solution' => 'A Flutter app that models plate appearances, runners, innings and pitching, stores games and generates information ready to review or share.',
            'stack' => ['Flutter','Dart','Google Drive','PDF','Excel','IAP'], 'signal' => 'Cloud backup, Free/Pro, AdMob and IAP',
            'context' => 'The challenge was not just displaying a score: the game itself had to be modeled. The app tracks plate appearances, runners, outs, innings and pitching to turn sports events into persistent state and statistics.',
            'capabilities' => ['Play-by-play scoring','Runner and out control','Inning summary','Pitcher statistics','Saved games and cumulative statistics','PDF and Excel export','Google Drive backup and restore','Free/Pro model with IAP and advertising'],
            'architecture' => ['Flutter/Dart for the Android application','Game state modeled around plate appearances, runners and innings','SharedPreferences for configuration and persistent snapshots','Google Drive API for backup/restore','PDF and Excel generation','Non-consumable in-app purchase and AdMob monetization'],
            'media' => [],
        ],
        [
            'name' => 'DocTotal', 'slug' => 'doctotal', 'type' => 'SaaS', 'status' => 'In development',
            'summary' => 'A SaaS platform for centralizing document and operational workflows with a maintainable, auditable Laravel architecture.',
            'problem' => 'Fragmented processes, scattered documents and limited operational traceability.',
            'solution' => 'A centralized product with clear workflows, security, auditing and modular growth.',
            'stack' => ['Laravel','PHP','Blade','MySQL'], 'signal' => 'Development with CI, Jira and PR review',
            'context' => 'DocTotal is being built as a SaaS product that must grow without losing traceability. It combines document workflows, account security, subscriptions and auditing with a delivery discipline based on tickets and CI.',
            'capabilities' => ['Structured document management','Account and security flows','Subscriptions and payments','Event auditing','Evolving multi-tenant architecture','Automated testing and CI'],
            'architecture' => ['Laravel 13 / PHP 8.4','Blade for the web interface','Relational persistence','Services and domains separated by responsibility','GitHub Actions for continuous validation','Jira + PR review for delivery traceability'],
            'media' => [],
        ],
        [
            'name' => 'URPE Gestión Clínica', 'slug' => 'urpe-gestion-clinica', 'type' => 'Clinical Software', 'status' => 'In development',
            'summary' => 'A clinical management system for organizing schedules, therapists, patients and operational appointment follow-up.',
            'problem' => 'Clinical operations need to coordinate availability, schedules and follow-up without losing context.',
            'solution' => 'A platform designed around the real care workflow, with integrated scheduling and clinical management.',
            'stack' => ['Laravel','PHP','Blade','MySQL'], 'signal' => 'Clinical workflows built incrementally',
            'context' => 'URPE Gestión Clínica is designed around how a center actually works: therapists with real availability, appointments within allowed hours and clinical follow-up tied to each visit.',
            'capabilities' => ['Therapist management','Weekly availability','Appointment scheduling','Schedule and overlap validations','Clinical follow-up and appointment log','Administrative workflows linked to care'],
            'architecture' => ['Laravel as the application and domain foundation','Availability and appointment models with explicit rules','Blade for administrative operation','MySQL for clinical and operational persistence','Feature tests for critical scheduling rules'],
            'media' => [],
        ],
        [
            'name' => 'AcadControl', 'slug' => 'acadcontrol', 'type' => 'Academic Management', 'status' => 'Product',
            'summary' => 'A suite for managing students, recurring fees, payments, records, receipts, notifications and online-learning integration.',
            'problem' => 'Recurring billing, records, communication and academic platforms often live in separate tools.',
            'solution' => 'A modular ecosystem where AcadControl centralizes operations and extends them through AcadNotify and ChamiloBridge.',
            'stack' => ['PHP','MySQL','WhatsApp','Chamilo API'], 'signal' => 'Suite: AcadControl + AcadNotify + ChamiloBridge',
            'context' => 'AcadControl was created to close the operating loop of an academy: know who is enrolled, what they owe, what they paid, what documents they have and how to keep communication and academic platforms connected.',
            'capabilities' => ['Student management','Recurring fees and payments','Payment periods or validity windows','Receipts and student records','Operational dashboards','Reminders and notifications with AcadNotify','LMS integration through ChamiloBridge'],
            'architecture' => ['PHP and MySQL for academic operations','Modules separated by responsibility','AcadControl as the student and payments core','AcadNotify for communication and reminders','ChamiloBridge for LMS integration through API','Reusable administrative configuration and tools'],
            'media' => [],
        ],
    ],
    'other_projects' => [
        ['name'=>'PartyX','slug'=>'partyx','type'=>'Interactive Events','status'=>'Product','summary'=>'Interactive digital invitations with RSVP and a control panel for managing guests.','stack'=>['Laravel','Blade','JavaScript','WhatsApp'],'signal'=>'RSVP + guest management panel'],
    ],
];
