<?php

return [
    'projects' => [
        [
            'name' => 'Citas CRIT',
            'slug' => 'citas-crit',
            'type' => 'Mobile App',
            'status' => 'Producción',
            'summary' => 'Una app Android pensada para ayudar a familias del CRIT a organizar y consultar sus citas de forma clara y práctica.',
            'problem' => 'La información de citas puede ser difícil de consultar y organizar en el día a día.',
            'solution' => 'Una experiencia móvil enfocada en claridad, acceso rápido y utilidad real para las familias.',
            'stack' => ['Flutter', 'Dart', 'Android'],
            'signal' => 'Publicada en Google Play',
        ],
        [
            'name' => 'Digital Persona SchoolBio',
            'slug' => 'digital-persona-schoolbio',
            'type' => 'Biometrics · Desktop',
            'status' => 'Producto',
            'summary' => 'Control biométrico escolar que conecta lectores de huella, una terminal Windows y servicios de plataforma para registrar asistencia e identidad.',
            'problem' => 'El control escolar presencial necesita identificar alumnos con rapidez y mantener la información sincronizada con la plataforma.',
            'solution' => 'Un cliente biométrico con enrolamiento, verificación e identificación por huella, operación local y sincronización mediante SchoolBio API.',
            'stack' => ['C#', 'WinForms', '.NET Framework 4.8', 'Biometría', 'API'],
            'signal' => 'Software + hardware biométrico + API',
        ],
        [
            'name' => 'Baseball App',
            'slug' => 'baseball-app',
            'type' => 'Mobile Product',
            'status' => 'Producto',
            'summary' => 'Anotador de béisbol para Android con seguimiento jugada a jugada, estadísticas, exportaciones y una experiencia Free/Pro.',
            'problem' => 'Registrar un juego completo y convertir cada jugada en estadísticas útiles suele requerir herramientas separadas o procesos manuales.',
            'solution' => 'Una app Flutter que modela turnos, corredores, innings y pitcheo, conserva juegos y genera información lista para consultar o compartir.',
            'stack' => ['Flutter', 'Dart', 'Google Drive', 'PDF', 'Excel', 'IAP'],
            'signal' => 'Backup en nube, Free/Pro, AdMob e IAP',
        ],
        [
            'name' => 'DocTotal',
            'slug' => 'doctotal',
            'type' => 'SaaS',
            'status' => 'En desarrollo',
            'summary' => 'Plataforma SaaS para centralizar procesos documentales y operativos con una arquitectura Laravel mantenible y auditable.',
            'problem' => 'Procesos fragmentados, documentos dispersos y poca trazabilidad operativa.',
            'solution' => 'Un producto centralizado con flujos claros, seguridad, auditoría y crecimiento por módulos.',
            'stack' => ['Laravel', 'PHP', 'Blade', 'MySQL'],
            'signal' => 'Desarrollo con CI, Jira y revisión por PR',
        ],
        [
            'name' => 'URPE Gestión Clínica',
            'slug' => 'urpe-gestion-clinica',
            'type' => 'Clinical Software',
            'status' => 'En desarrollo',
            'summary' => 'Sistema de gestión clínica para organizar agenda, terapeutas, pacientes y seguimiento operativo de citas.',
            'problem' => 'La operación clínica necesita coordinar disponibilidad, horarios y seguimiento sin perder contexto.',
            'solution' => 'Una plataforma orientada al flujo real de atención, con agenda y gestión clínica integradas.',
            'stack' => ['Laravel', 'PHP', 'Blade', 'MySQL'],
            'signal' => 'Flujos clínicos construidos por etapas',
        ],
        [
            'name' => 'AcadControl',
            'slug' => 'acadcontrol',
            'type' => 'Academic Management',
            'status' => 'Producto',
            'summary' => 'Suite para administrar alumnos, mensualidades, pagos, expedientes, recibos, notificaciones e integración con aprendizaje en línea.',
            'problem' => 'Cobros periódicos, expedientes, comunicación y plataformas académicas suelen vivir en herramientas separadas.',
            'solution' => 'Un ecosistema modular donde AcadControl centraliza la operación y se extiende con AcadNotify y ChamiloBridge.',
            'stack' => ['PHP', 'MySQL', 'WhatsApp', 'Chamilo API'],
            'signal' => 'Suite: AcadControl + AcadNotify + ChamiloBridge',
        ],
    ],
    'other_projects' => [
        [
            'name' => 'PartyX',
            'slug' => 'partyx',
            'type' => 'Interactive Events',
            'status' => 'Producto',
            'summary' => 'Invitaciones digitales interactivas con confirmación de asistencia y panel de control para gestionar invitados.',
            'stack' => ['Laravel', 'Blade', 'JavaScript', 'WhatsApp'],
            'signal' => 'RSVP + panel de invitados',
        ],
    ],
];
