<?php

return [
    'projects' => [
        [
            'name' => 'Citas CRIT',
            'slug' => 'citas-crit',
            'type' => 'Mobile App',
            'status' => 'Producción',
            'summary' => 'Una app Android pensada para ayudar a familias del CRIT a organizar y consultar sus citas de forma clara y práctica.',
            'problem' => 'La información de citas puede ser difícil de consultar y organizar en el día a día.',
            'solution' => 'Una experiencia móvil enfocada en claridad, acceso rápido y utilidad real para las familias.',
            'stack' => ['Flutter', 'Dart', 'Android'],
            'signal' => 'Publicada en Google Play',
            'context' => 'El producto nació de una necesidad cotidiana: tener las citas del CRIT organizadas en un lugar accesible, con una experiencia simple para familias que necesitan consultar información sin fricción.',
            'capabilities' => ['Importación y organización de agenda', 'Consulta clara de citas', 'Persistencia local de información', 'Distribución como app Android'],
            'architecture' => ['Flutter para una experiencia móvil consistente', 'Persistencia local para mantener la agenda disponible', 'Procesamiento de la información de citas dentro de la app', 'Publicación y actualización mediante Google Play'],
            'media' => [],
        ],
        [
            'name' => 'Digital Persona SchoolBio',
            'slug' => 'digital-persona-schoolbio',
            'type' => 'Biometrics · Desktop',
            'status' => 'Producto',
            'summary' => 'Control biométrico escolar que conecta lectores de huella, una terminal Windows y servicios de plataforma para registrar asistencia e identidad.',
            'problem' => 'El control escolar presencial necesita identificar alumnos con rapidez y mantener la información sincronizada con la plataforma.',
            'solution' => 'Un cliente biométrico con enrolamiento, verificación e identificación por huella, operación local y sincronización mediante SchoolBio API.',
            'stack' => ['C#', 'WinForms', '.NET Framework 4.8', 'Biometría', 'API'],
            'signal' => 'Software + hardware biométrico + API',
            'context' => 'SchoolBio extiende el software escolar hasta el punto físico de entrada: una terminal Windows conversa con el lector biométrico, administra datos locales y sincroniza eventos con la plataforma.',
            'capabilities' => ['Enrolamiento de huellas', 'Verificación e identificación biométrica', 'Registro de asistencia', 'Gestión de alumnos y periodos académicos', 'Sincronización con SchoolBio API'],
            'architecture' => ['Cliente C# / Windows Forms sobre .NET Framework 4.8', 'Integración con hardware Digital Persona', 'Repositorios locales para operación de terminal', 'Servicios biométricos para enrolamiento e identificación', 'API para sincronización con la plataforma SchoolBio'],
            'media' => [],
        ],
        [
            'name' => 'Baseball App',
            'slug' => 'baseball-app',
            'type' => 'Mobile Product',
            'status' => 'Producto',
            'summary' => 'Anotador de béisbol para Android con seguimiento jugada a jugada, estadísticas, exportaciones y una experiencia Free/Pro.',
            'problem' => 'Registrar un juego completo y convertir cada jugada en estadísticas útiles suele requerir herramientas separadas o procesos manuales.',
            'solution' => 'Una app Flutter que modela turnos, corredores, innings y pitcheo, conserva juegos y genera información lista para consultar o compartir.',
            'stack' => ['Flutter', 'Dart', 'Google Drive', 'PDF', 'Excel', 'IAP'],
            'signal' => 'Backup en nube, Free/Pro, AdMob e IAP',
            'context' => 'El reto no era solo mostrar un marcador: había que modelar el juego. La app sigue apariciones al plato, corredores, outs, entradas y pitcheo para convertir eventos deportivos en estado y estadísticas persistentes.',
            'capabilities' => ['Scoring jugada a jugada', 'Control de corredores y outs', 'Resumen por inning', 'Estadísticas de pitcher', 'Juegos guardados y estadísticas acumuladas', 'Exportación PDF y Excel', 'Backup y restore en Google Drive', 'Modelo Free/Pro con IAP y publicidad'],
            'architecture' => ['Flutter/Dart para la aplicación Android', 'Estado de juego modelado alrededor de turnos, corredores e innings', 'SharedPreferences para configuración y snapshots persistentes', 'Google Drive API para backup/restore', 'Generación de PDF y Excel', 'In-app purchase no consumible y AdMob para monetización'],
            'media' => [],
        ],
        [
            'name' => 'DocTotal',
            'slug' => 'doctotal',
            'type' => 'SaaS',
            'status' => 'En desarrollo',
            'summary' => 'Plataforma SaaS para centralizar procesos documentales y operativos con una arquitectura Laravel mantenible y auditable.',
            'problem' => 'Procesos fragmentados, documentos dispersos y poca trazabilidad operativa.',
            'solution' => 'Un producto centralizado con flujos claros, seguridad, auditoría y crecimiento por módulos.',
            'stack' => ['Laravel', 'PHP', 'Blade', 'MySQL'],
            'signal' => 'Desarrollo con CI, Jira y revisión por PR',
            'context' => 'DocTotal se construye como un SaaS que debe crecer sin perder trazabilidad. El producto combina procesos documentales, seguridad de cuenta, suscripciones y auditoría con una disciplina de entrega basada en tickets y CI.',
            'capabilities' => ['Gestión documental estructurada', 'Flujos de seguridad y cuenta', 'Suscripciones y pagos', 'Auditoría de eventos', 'Arquitectura multi-tenant en evolución', 'Pruebas automatizadas y CI'],
            'architecture' => ['Laravel 13 / PHP 8.4', 'Blade para la interfaz web', 'Persistencia relacional', 'Servicios y dominios separados por funcionalidad', 'GitHub Actions para validación continua', 'Jira + PR review como trazabilidad de entrega'],
            'media' => [],
        ],
        [
            'name' => 'URPE Gestión Clínica',
            'slug' => 'urpe-gestion-clinica',
            'type' => 'Clinical Software',
            'status' => 'En desarrollo',
            'summary' => 'Sistema de gestión clínica para organizar agenda, terapeutas, pacientes y seguimiento operativo de citas.',
            'problem' => 'La operación clínica necesita coordinar disponibilidad, horarios y seguimiento sin perder contexto.',
            'solution' => 'Una plataforma orientada al flujo real de atención, con agenda y gestión clínica integradas.',
            'stack' => ['Laravel', 'PHP', 'Blade', 'MySQL'],
            'signal' => 'Flujos clínicos construidos por etapas',
            'context' => 'URPE Gestión Clínica se diseña alrededor de cómo trabaja un centro: terapeutas con disponibilidad real, citas dentro de horarios permitidos y seguimiento clínico asociado a cada atención.',
            'capabilities' => ['Gestión de terapeutas', 'Disponibilidad semanal', 'Agenda de citas', 'Validaciones de horario y traslapes', 'Seguimiento y bitácora clínica', 'Flujos administrativos vinculados a atención'],
            'architecture' => ['Laravel como base de dominio y aplicación', 'Modelos de disponibilidad y citas con reglas explícitas', 'Blade para operación administrativa', 'MySQL para persistencia clínica y operativa', 'Pruebas Feature para reglas críticas de agenda'],
            'media' => [],
        ],
        [
            'name' => 'AcadControl',
            'slug' => 'acadcontrol',
            'type' => 'Academic Management',
            'status' => 'Producto',
            'summary' => 'Suite para administrar alumnos, mensualidades, pagos, expedientes, recibos, notificaciones e integración con aprendizaje en línea.',
            'problem' => 'Cobros periódicos, expedientes, comunicación y plataformas académicas suelen vivir en herramientas separadas.',
            'solution' => 'Un ecosistema modular donde AcadControl centraliza la operación y se extiende con AcadNotify y ChamiloBridge.',
            'stack' => ['PHP', 'MySQL', 'WhatsApp', 'Chamilo API'],
            'signal' => 'Suite: AcadControl + AcadNotify + ChamiloBridge',
            'context' => 'AcadControl nació para cerrar el ciclo operativo de una academia: saber quién estudia, qué debe pagar, qué pagó, qué documentos tiene y cómo mantener comunicación y plataformas académicas conectadas.',
            'capabilities' => ['Gestión de alumnos', 'Mensualidades y cobros periódicos', 'Periodos o vigencias de pago', 'Recibos y expedientes', 'Dashboards operativos', 'Recordatorios y notificaciones con AcadNotify', 'Integración LMS mediante ChamiloBridge'],
            'architecture' => ['PHP y MySQL para la operación académica', 'Módulos separados por responsabilidad', 'AcadControl como núcleo de alumnos y pagos', 'AcadNotify para comunicación y recordatorios', 'ChamiloBridge para integración con LMS vía API', 'Configuración y herramientas administrativas reutilizables'],
            'media' => [],
        ],
    ],
    'other_projects' => [
        [
            'name' => 'PartyX',
            'slug' => 'partyx',
            'type' => 'Interactive Events',
            'status' => 'Producto',
            'summary' => 'Invitaciones digitales interactivas con confirmación de asistencia y panel de control para gestionar invitados.',
            'stack' => ['Laravel', 'Blade', 'JavaScript', 'WhatsApp'],
            'signal' => 'RSVP + panel de invitados',
        ],
    ],
];
